# Generated by Django 5.2.1 on 2025-06-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Full_Learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
